name: genome_assembly_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - sra-tools=3.0.0
  - fastqc=0.11.9
  - trimmomatic=0.39
  - spades=3.15.5
  - quast=5.2.0
  - dfast
  - tbl2asn=25.7
